using System.Numerics;
using Content.Shared._Stalker_EN.FactionRelations;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Utility;

namespace Content.Client._Stalker_EN.FactionRelations;

[GenerateTypedNameReferences]
public sealed partial class FactionRelationsUiFragment : BoxContainer
{
    private static readonly ResPath PatchRsiPath = new("/Textures/_Stalker/Icons/Patches/band.rsi");
    private static readonly ResPath PatchRsiPathEN = new("/Textures/_Stalker_EN/Icons/Patches/band.rsi");

    /// <summary>
    /// RSI paths and state names for faction patch icons in the grid headers.
    /// </summary>
    private static readonly Dictionary<string, (ResPath Rsi, string State)> FactionPatchStates = new()
    {
        ["Loners"] = (PatchRsiPath, "stalker"),
        ["Freedom"] = (PatchRsiPath, "freedom"),
        ["Bandits"] = (PatchRsiPath, "band"),
        ["Duty"] = (PatchRsiPath, "dolg"),
        ["Ecologist"] = (PatchRsiPath, "ecologist"),
        ["Neutrals"] = (PatchRsiPath, "ne"),
        ["Mercenaries"] = (PatchRsiPath, "merc"),
        ["Military"] = (PatchRsiPath, "army"),
        ["Monolith"] = (PatchRsiPath, "monolith"),
        ["ClearSky"] = (PatchRsiPath, "cn"),
        ["Renegades"] = (PatchRsiPath, "rene"),
        ["Rookies"] = (PatchRsiPathEN, "rookie"),
    };

    private static readonly ResPath AllyIconPath = new("/Textures/_Stalker_EN/Interface/FactionRelations/ally.png");
    private static readonly ResPath NeutralIconPath = new("/Textures/_Stalker_EN/Interface/FactionRelations/neutral.png");
    private static readonly ResPath HostileIconPath = new("/Textures/_Stalker_EN/Interface/FactionRelations/hostile.png");
    private static readonly ResPath WarIconPath = new("/Textures/_Stalker_EN/Interface/FactionRelations/war.png");

    private static readonly Dictionary<STFactionRelationType, (ResPath Icon, string Name)> RelationIcons = new()
    {
        [STFactionRelationType.Alliance] = (AllyIconPath, "Alliance"),
        [STFactionRelationType.Neutral] = (NeutralIconPath, "Neutral"),
        [STFactionRelationType.Hostile] = (HostileIconPath, "Hostile"),
        [STFactionRelationType.War] = (WarIconPath, "War"),
    };

    private static readonly Color SelfColor = Color.FromHex("#333333");
    private static readonly Color HeaderColor = Color.FromHex("#1a1a2e");

    private SpriteSystem? _spriteSystem;

    public FactionRelationsUiFragment()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(STFactionRelationsUiState state)
    {
        RelationsGrid.RemoveAllChildren();

        var factions = state.FactionIds;
        if (factions.Count == 0)
            return;

        // Build a lookup from the flat list
        var lookup = new Dictionary<(string, string), STFactionRelationType>();
        foreach (var entry in state.Relations)
        {
            lookup[(entry.FactionA, entry.FactionB)] = entry.Relation;
        }

        var columns = factions.Count + 1;
        RelationsGrid.Columns = columns;

        _spriteSystem ??= IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();

        // Top-left empty corner cell
        AddCell("", HeaderColor);

        // Header row
        foreach (var faction in factions)
        {
            AddHeaderCell(faction, HeaderColor, _spriteSystem);
        }

        // Data rows
        foreach (var rowFaction in factions)
        {
            // Row header
            AddHeaderCell(rowFaction, HeaderColor, _spriteSystem);

            foreach (var colFaction in factions)
            {
                if (rowFaction == colFaction)
                {
                    AddCell("-", SelfColor);
                    continue;
                }

                var key = STFactionRelationHelpers.NormalizePair(rowFaction, colFaction);
                var relation = lookup.GetValueOrDefault(key, STFactionRelationType.Neutral);
                AddRelationCell(relation, _spriteSystem!);
            }
        }
    }

    private void AddHeaderCell(string faction, Color bgColor, SpriteSystem spriteSystem)
    {
        var panel = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = bgColor,
                ContentMarginLeftOverride = 2,
                ContentMarginRightOverride = 2,
                ContentMarginTopOverride = 2,
                ContentMarginBottomOverride = 2,
            },
            MinSize = new Vector2(32, 20),
            HorizontalExpand = true,
            ToolTip = faction,
        };

        if (FactionPatchStates.TryGetValue(faction, out var patch))
        {
            var specifier = new SpriteSpecifier.Rsi(patch.Rsi, patch.State);
            var textureRect = new TextureRect
            {
                Texture = spriteSystem.Frame0(specifier),
                TextureScale = new Vector2(1.5f, 1.5f),
                Stretch = TextureRect.StretchMode.KeepCentered,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
            };
            panel.AddChild(textureRect);
        }
        else
        {
            var label = new Label
            {
                Text = faction[..Math.Min(3, faction.Length)],
                FontColorOverride = Color.White,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
            };
            panel.AddChild(label);
        }

        RelationsGrid.AddChild(panel);
    }

    private void AddCell(string text, Color bgColor)
    {
        var panel = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = bgColor,
                ContentMarginLeftOverride = 2,
                ContentMarginRightOverride = 2,
                ContentMarginTopOverride = 1,
                ContentMarginBottomOverride = 1,
            },
            MinSize = new Vector2(32, 20),
            HorizontalExpand = true,
        };

        var label = new Label
        {
            Text = text,
            FontColorOverride = Color.White,
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
        };

        panel.AddChild(label);
        RelationsGrid.AddChild(panel);
    }

    private void AddRelationCell(STFactionRelationType relation, SpriteSystem spriteSystem)
    {
        var (iconPath, name) = RelationIcons.GetValueOrDefault(relation, RelationIcons[STFactionRelationType.Neutral]);
        var specifier = new SpriteSpecifier.Texture(iconPath);

        var panel = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.Transparent,
                ContentMarginLeftOverride = 2,
                ContentMarginRightOverride = 2,
                ContentMarginTopOverride = 2,
                ContentMarginBottomOverride = 2,
            },
            MinSize = new Vector2(32, 20),
            HorizontalExpand = true,
            ToolTip = name,
        };

        var textureRect = new TextureRect
        {
            Texture = spriteSystem.Frame0(specifier),
            TextureScale = new Vector2(1.5f, 1.5f),
            Stretch = TextureRect.StretchMode.KeepCentered,
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
        };

        panel.AddChild(textureRect);
        RelationsGrid.AddChild(panel);
    }
}
