using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stalker_EN.PdaMessenger;

/// <summary>
/// A contact row in the main page's contact list, showing name, messenger ID, and unread badge.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class STMessengerContactRow : BoxContainer
{
    /// <summary>Raised when the user clicks the contact row to open the DM conversation.</summary>
    public event Action? OnSelected;

    /// <summary>Raised when the user clicks the remove button to delete this contact.</summary>
    public event Action? OnRemove;

    public STMessengerContactRow(string contactName, int unreadCount, string? messengerId)
    {
        RobustXamlLoader.Load(this);

        ContactNameLabel.Text = contactName;

        PdaIdLabel.Text = messengerId ?? string.Empty;
        PdaIdLabel.Visible = messengerId is not null;

        UnreadLabel.Text = unreadCount > 0
            ? Loc.GetString("st-messenger-unread-count", ("count", unreadCount))
            : string.Empty;
        UnreadLabel.Visible = unreadCount > 0;

        SelectButton.OnPressed += _ => OnSelected?.Invoke();
        RemoveButton.OnPressed += _ => OnRemove?.Invoke();
    }
}
