using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Stalker_EN.PdaMessenger;

/// <summary>
/// A contact row in the main page's contact list, showing name, messenger ID, faction icon, and unread badge.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class STMessengerContactRow : BoxContainer
{
    /// <summary>RSI path for EN-fork faction patches (checked first).</summary>
    private static readonly ResPath BandRsiPathEN = new("/Textures/_Stalker_EN/Icons/Patches/band.rsi");

    /// <summary>RSI path for upstream faction patches (fallback).</summary>
    private static readonly ResPath BandRsiPath = new("/Textures/_Stalker/Icons/Patches/band.rsi");

    private SpriteSystem? _spriteSystem;
    private IResourceCache? _resCache;

    /// <summary>Raised when the user clicks the contact row to open the DM conversation.</summary>
    public event Action? OnSelected;

    /// <summary>Raised when the user clicks the remove button to delete this contact.</summary>
    public event Action? OnRemove;

    public STMessengerContactRow(string contactName, int unreadCount, string? messengerId, string? bandIcon)
    {
        RobustXamlLoader.Load(this);

        ContactNameLabel.Text = contactName;

        PdaIdLabel.Text = messengerId ?? string.Empty;
        PdaIdLabel.Visible = messengerId is not null;

        UnreadLabel.Text = unreadCount > 0
            ? Loc.GetString("st-messenger-unread-count", ("count", unreadCount))
            : string.Empty;
        UnreadLabel.Visible = unreadCount > 0;

        if (bandIcon is not null)
        {
            _spriteSystem ??= IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();
            _resCache ??= IoCManager.Resolve<IResourceCache>();

            // Try _Stalker_EN path first, fall back to _Stalker
            var rsiPath = BandRsiPath;
            if (_resCache.TryGetResource<RSIResource>(BandRsiPathEN, out var enRsi)
                && enRsi.RSI.TryGetState(bandIcon, out _))
            {
                rsiPath = BandRsiPathEN;
            }

            var specifier = new SpriteSpecifier.Rsi(rsiPath, bandIcon);
            FactionPatch.Texture = _spriteSystem.Frame0(specifier);
        }
        else
        {
            FactionPatch.Visible = false;
        }

        SelectButton.OnPressed += _ => OnSelected?.Invoke();
        RemoveButton.OnPressed += _ => OnRemove?.Invoke();
    }
}
